### ISSUE TITLE
TLS certificate expired. Configure Github free HTTPS?

### ISSUE THREAD

**Issue by zerjioang** [blockchaingalicia/landing-page#4]
Hi guys,

your certificate of the site is expired as shown here:

```bash
blockchain.gal uses an invalid security certificate.
The certificate expired on March 12, 2019, 12:00:31 AM GMT+1.
The current time is March 15, 2019, 9:41 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

Since you are hosting a static files site using Github pages, why dont you configure GIthub free SSL via Lets encrypt on your site and forget about certs renewal?

**Comment by brunneis** [comment]
Thank you @zerjioang for pointing it out. Currently, the landing page is running a Wordpress instance so we manage the certificates ourselves. It'll be fixed and automated soon with https://github.com/brunneis/https-reverse-proxy 🎉
